export const CONTINENTS = [
  'Africa',
  'Asia',
  'Europe',
  'North America',
  'South America',
  'Oceania',
  'Antarctica',
] as const

export type Continent = (typeof CONTINENTS)[number]

const COUNTRY_TO_CONTINENT: Record<string, Continent> = {
  ad: 'Europe',
  ae: 'Asia',
  af: 'Asia',
  ag: 'North America',
  ai: 'North America',
  al: 'Europe',
  am: 'Asia',
  ao: 'Africa',
  aq: 'Antarctica',
  ar: 'South America',
  as: 'Oceania',
  at: 'Europe',
  au: 'Oceania',
  aw: 'North America',
  ax: 'Europe',
  az: 'Asia',
  ba: 'Europe',
  bb: 'North America',
  bd: 'Asia',
  be: 'Europe',
  bf: 'Africa',
  bg: 'Europe',
  bh: 'Asia',
  bi: 'Africa',
  bj: 'Africa',
  bl: 'North America',
  bm: 'North America',
  bn: 'Asia',
  bo: 'South America',
  bq: 'North America',
  br: 'South America',
  bs: 'North America',
  bt: 'Asia',
  bv: 'Antarctica',
  bw: 'Africa',
  by: 'Europe',
  bz: 'North America',
  ca: 'North America',
  cc: 'Asia',
  cd: 'Africa',
  cf: 'Africa',
  cg: 'Africa',
  ch: 'Europe',
  ci: 'Africa',
  ck: 'Oceania',
  cl: 'South America',
  cm: 'Africa',
  cn: 'Asia',
  co: 'South America',
  cr: 'North America',
  cu: 'North America',
  cv: 'Africa',
  cw: 'North America',
  cx: 'Asia',
  cy: 'Asia',
  cz: 'Europe',
  de: 'Europe',
  dj: 'Africa',
  dk: 'Europe',
  dm: 'North America',
  do: 'North America',
  dz: 'Africa',
  ec: 'South America',
  ee: 'Europe',
  eg: 'Africa',
  eh: 'Africa',
  er: 'Africa',
  es: 'Europe',
  et: 'Africa',
  fi: 'Europe',
  fj: 'Oceania',
  fk: 'South America',
  fm: 'Oceania',
  fo: 'Europe',
  fr: 'Europe',
  ga: 'Africa',
  gb: 'Europe',
  gd: 'North America',
  ge: 'Asia',
  gf: 'South America',
  gg: 'Europe',
  gh: 'Africa',
  gi: 'Europe',
  gl: 'North America',
  gm: 'Africa',
  gn: 'Africa',
  gp: 'North America',
  gq: 'Africa',
  gr: 'Europe',
  gs: 'Antarctica',
  gt: 'North America',
  gu: 'Oceania',
  gw: 'Africa',
  gy: 'South America',
  hk: 'Asia',
  hm: 'Antarctica',
  hn: 'North America',
  hr: 'Europe',
  ht: 'North America',
  hu: 'Europe',
  id: 'Asia',
  ie: 'Europe',
  il: 'Asia',
  im: 'Europe',
  in: 'Asia',
  io: 'Asia',
  iq: 'Asia',
  ir: 'Asia',
  is: 'Europe',
  it: 'Europe',
  je: 'Europe',
  jm: 'North America',
  jo: 'Asia',
  jp: 'Asia',
  ke: 'Africa',
  kg: 'Asia',
  kh: 'Asia',
  ki: 'Oceania',
  km: 'Africa',
  kn: 'North America',
  kp: 'Asia',
  kr: 'Asia',
  kw: 'Asia',
  ky: 'North America',
  kz: 'Asia',
  la: 'Asia',
  lb: 'Asia',
  lc: 'North America',
  li: 'Europe',
  lk: 'Asia',
  lr: 'Africa',
  ls: 'Africa',
  lt: 'Europe',
  lu: 'Europe',
  lv: 'Europe',
  ly: 'Africa',
  ma: 'Africa',
  mc: 'Europe',
  md: 'Europe',
  me: 'Europe',
  mf: 'North America',
  mg: 'Africa',
  mh: 'Oceania',
  mk: 'Europe',
  ml: 'Africa',
  mm: 'Asia',
  mn: 'Asia',
  mo: 'Asia',
  mp: 'Oceania',
  mq: 'North America',
  mr: 'Africa',
  ms: 'North America',
  mt: 'Europe',
  mu: 'Africa',
  mv: 'Asia',
  mw: 'Africa',
  mx: 'North America',
  my: 'Asia',
  mz: 'Africa',
  na: 'Africa',
  nc: 'Oceania',
  ne: 'Africa',
  nf: 'Oceania',
  ng: 'Africa',
  ni: 'North America',
  nl: 'Europe',
  no: 'Europe',
  np: 'Asia',
  nr: 'Oceania',
  nu: 'Oceania',
  nz: 'Oceania',
  om: 'Asia',
  pa: 'North America',
  pe: 'South America',
  pf: 'Oceania',
  pg: 'Oceania',
  ph: 'Asia',
  pk: 'Asia',
  pl: 'Europe',
  pm: 'North America',
  pn: 'Oceania',
  pr: 'North America',
  ps: 'Asia',
  pt: 'Europe',
  pw: 'Oceania',
  py: 'South America',
  qa: 'Asia',
  re: 'Africa',
  ro: 'Europe',
  rs: 'Europe',
  ru: 'Europe',
  rw: 'Africa',
  sa: 'Asia',
  sb: 'Oceania',
  sc: 'Africa',
  sd: 'Africa',
  se: 'Europe',
  sg: 'Asia',
  sh: 'Africa',
  si: 'Europe',
  sj: 'Europe',
  sk: 'Europe',
  sl: 'Africa',
  sm: 'Europe',
  sn: 'Africa',
  so: 'Africa',
  sr: 'South America',
  ss: 'Africa',
  st: 'Africa',
  sv: 'North America',
  sx: 'North America',
  sy: 'Asia',
  sz: 'Africa',
  tc: 'North America',
  td: 'Africa',
  tf: 'Antarctica',
  tg: 'Africa',
  th: 'Asia',
  tj: 'Asia',
  tk: 'Oceania',
  tl: 'Asia',
  tm: 'Asia',
  tn: 'Africa',
  to: 'Oceania',
  tr: 'Asia',
  tt: 'North America',
  tv: 'Oceania',
  tw: 'Asia',
  tz: 'Africa',
  ua: 'Europe',
  ug: 'Africa',
  um: 'Oceania',
  us: 'North America',
  uy: 'South America',
  uz: 'Asia',
  va: 'Europe',
  vc: 'North America',
  ve: 'South America',
  vg: 'North America',
  vi: 'North America',
  vn: 'Asia',
  vu: 'Oceania',
  wf: 'Oceania',
  ws: 'Oceania',
  ye: 'Asia',
  yt: 'Africa',
  za: 'Africa',
  zm: 'Africa',
  zw: 'Africa',
}

export function getContinentByCountryCode(countryCode: string | null): Continent | null {
  if (!countryCode) return null
  return COUNTRY_TO_CONTINENT[countryCode.toLowerCase()] ?? null
}
